"""
PDF预处理配置
存储API Token和其他配置信息
"""

# API配置
MINERU_API_TOKEN = "eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJqdGkiOiIyMzYwMDkyMyIsInJvbCI6IlJPTEVfUkVHSVNURVIiLCJpc3MiOiJPcGVuWExhYiIsImlhdCI6MTc2NzE5MTM0NiwiY2xpZW50SWQiOiJsa3pkeDU3bnZ5MjJqa3BxOXgydyIsInBob25lIjoiIiwib3BlbklkIjpudWxsLCJ1dWlkIjoiNmRmMWZhNmMtMDk2ZC00MGQwLTlmYWYtN2E4M2M3NmNiZjY2IiwiZW1haWwiOiIiLCJleHAiOjE3Njg0MDA5NDZ9.1IpNQ9madLeuqXxB-FjZcNPVhtyl5yy8iZibKRSpH7AaQ6ebgBEbf8E5032kjxaN46KRaF4Xiu36haWZco1ZUA"

# 云服务器配置
CLOUD_SERVER_IP = "175.24.233.134"
CLOUD_SERVER_PORT = 3389
CLOUD_SERVER_URL = f"http://{CLOUD_SERVER_IP}:{CLOUD_SERVER_PORT}"
USE_OWN_CLOUD_SERVER = True  # 使用自己的云服务器

# 处理配置
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
MAX_CONTEXT_LENGTH = 8000
ENABLE_CLEANING = True
ENABLE_SPLITTING = True
ENABLE_PROMPT_BUILDING = True

# 语言配置
LANGUAGE = "zh"
PROMPT_FORMAT_TYPE = "qa"

# 输出配置
OUTPUT_DIR = "./processed_output"